In [3]:
!pip install -q datasets pandas

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [4]:
from datasets import load_dataset

/Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# KPoEM 데이터셋(작품 단위) 로드
df_poem_ = load_dataset(
    "csv",  # csv 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_poem_dataset_v4.tsv",  # Hugging Face에 저장된 TSV 파일 경로
    },
    delimiter="\t",  # TSV 파일이므로 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
df_poem = df_poem_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
df_poem.head()

Generating train split: 615 examples [00:00, 28018.52 examples/s]

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움"
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정"
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심"
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침"
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함"

In [6]:
# KPoEM 데이터셋(행/시구 단위) 로드
df_line_ = load_dataset(
    "csv",  # CSV 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_line_dataset_v4.tsv",  # Hugging Face에 저장된 시구 단위 데이터 경로
    },
    delimiter="\t",  # 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용 가능)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
df_line = df_line_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
df_line.head()

Generating train split: 7007 examples [00:00, 110376.01 examples/s]

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔"
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감"
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오"
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복"

In [7]:
KOTE_EMOTION2IDX = {
    "불평/불만": 0,
    "환영/호의": 1,
    "감동/감탄": 2,
    "지긋지긋": 3,
    "고마움": 4,
    "슬픔": 5,
    "화남/분노": 6,
    "존경": 7,
    "기대감": 8,
    "우쭐댐/무시함": 9,
    "안타까움/실망": 10,
    "비장함": 11,
    "의심/불신": 12,
    "뿌듯함": 13,
    "편안/쾌적": 14,
    "신기함/관심": 15,
    "아껴주는": 16,
    "부끄러움": 17,
    "공포/무서움": 18,
    "절망": 19,
    "한심함": 20,
    "역겨움/징그러움": 21,
    "짜증": 22,
    "어이없음": 23,
    "없음": 24,
    "패배/자기혐오": 25,
    "귀찮음": 26,
    "힘듦/지침": 27,
    "즐거움/신남": 28,
    "깨달음": 29,
    "죄책감": 30,
    "증오/혐오": 31,
    "흐뭇함(귀여움/예쁨)": 32,
    "당황/난처": 33,
    "경악": 34,
    "부담/안_내킴": 35,
    "서러움": 36,
    "재미없음": 37,
    "불쌍함/연민": 38,
    "놀람": 39,
    "행복": 40,
    "불안/걱정": 41,
    "기쁨": 42,
    "안심/신뢰": 43
}

In [8]:
import pandas as pd

def emotion_str_to_index_list(emotion_str):
    if pd.isna(emotion_str):
        return []

    emotions = [e.strip() for e in emotion_str.split(",")]
    return [KOTE_EMOTION2IDX[e] for e in emotions if e in KOTE_EMOTION2IDX]

In [10]:
annotator_cols = [
    "annotator_01",
    "annotator_02",
    "annotator_03",
    "annotator_04",
    "annotator_05"
]

for col in annotator_cols:
    df_line[col + "_idx"] = df_line[col].apply(emotion_str_to_index_list)

In [12]:
for col in annotator_cols:
    df_poem[col + "_idx"] = df_poem[col].apply(emotion_str_to_index_list)

In [14]:
POET2IDX = {
    "김소월": 0,
    "윤동주": 1,
    "이상": 2,
    "임화": 3,
    "한용운": 4
}

In [15]:
df_line["poet_idx"] = df_line["poet"].map(POET2IDX)

In [16]:
df_poem["poet_idx"] = df_poem["poet"].map(POET2IDX)

In [17]:
df_line.head()

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔",[11],[11],"[13, 11]","[11, 13, 2]","[11, 36, 5]",1
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함,"[17, 11]","[17, 11, 8, 41, 36, 5]","[29, 11, 13]","[11, 17, 8]",[11],1
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감","[8, 15]","[8, 41, 11]","[5, 36, 41, 33]","[11, 5]","[2, 15, 14, 8]",1
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오","[19, 5, 25]","[19, 5, 25, 30, 27, 11]","[33, 36, 30, 25]","[11, 5, 25, 19, 27]","[5, 36, 19, 27, 25]",1
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복","[42, 15, 28, 32, 13]","[42, 13, 2, 5, 11, 16, 1, 8]","[4, 8, 42, 16, 32]","[2, 8, 42, 16, 40]","[28, 8, 42, 40]",1

In [19]:
df_poem.head()

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움","[41, 11, 36, 5, 10, 17, 30, 25]","[25, 36, 11, 17, 16, 5, 41, 30]","[29, 32, 4, 27, 10]","[11, 13, 5]","[11, 2, 29, 36]",1
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정","[38, 16, 15, 32, 36, 22, 3, 10]","[15, 31, 38, 6, 36, 5, 16, 25]","[10, 36, 5, 29, 32]","[0, 10, 12, 5]","[38, 41]",1
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심","[36, 25, 7, 2, 11, 38, 41, 30]","[2, 39, 38, 11, 5, 40, 16, 41]","[19, 29, 36, 27, 7, 11]","[33, 27, 39, 5, 41]","[29, 11, 7, 15]",1
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침","[5, 36, 20, 25, 30, 17]","[11, 36, 5, 41, 25, 30]","[27, 10, 36, 19, 29]","[27, 33, 41, 0, 5, 17, 25]","[29, 38, 41, 36, 25, 27]",1
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함","[38, 11, 18, 5, 36, 12, 29, 8]","[27, 39, 36, 5, 2, 7, 30, 25, 11, 16]","[19, 29, 36, 27, 10]","[5, 27, 19, 8, 10, 41]","[18, 33, 39, 41, 11]",1