In [3]:
!pip install -q datasets pandas

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [4]:
from datasets import load_dataset

/Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# KPoEM 데이터셋(작품 단위) 로드
df_poem_ = load_dataset(
    "csv",  # csv 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_poem_dataset_v4.tsv",  # Hugging Face에 저장된 TSV 파일 경로
    },
    delimiter="\t",  # TSV 파일이므로 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
df_poem = df_poem_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
df_poem.head()

Generating train split: 615 examples [00:00, 28018.52 examples/s]

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움"
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정"
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심"
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침"
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함"

In [6]:
# KPoEM 데이터셋(행/시구 단위) 로드
df_line_ = load_dataset(
    "csv",  # CSV 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_line_dataset_v4.tsv",  # Hugging Face에 저장된 시구 단위 데이터 경로
    },
    delimiter="\t",  # 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용 가능)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
df_line = df_line_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
df_line.head()

Generating train split: 7007 examples [00:00, 110376.01 examples/s]

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔"
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감"
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오"
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복"

In [7]:
KOTE_EMOTION2IDX = {
    "불평/불만": 0,
    "환영/호의": 1,
    "감동/감탄": 2,
    "지긋지긋": 3,
    "고마움": 4,
    "슬픔": 5,
    "화남/분노": 6,
    "존경": 7,
    "기대감": 8,
    "우쭐댐/무시함": 9,
    "안타까움/실망": 10,
    "비장함": 11,
    "의심/불신": 12,
    "뿌듯함": 13,
    "편안/쾌적": 14,
    "신기함/관심": 15,
    "아껴주는": 16,
    "부끄러움": 17,
    "공포/무서움": 18,
    "절망": 19,
    "한심함": 20,
    "역겨움/징그러움": 21,
    "짜증": 22,
    "어이없음": 23,
    "없음": 24,
    "패배/자기혐오": 25,
    "귀찮음": 26,
    "힘듦/지침": 27,
    "즐거움/신남": 28,
    "깨달음": 29,
    "죄책감": 30,
    "증오/혐오": 31,
    "흐뭇함(귀여움/예쁨)": 32,
    "당황/난처": 33,
    "경악": 34,
    "부담/안_내킴": 35,
    "서러움": 36,
    "재미없음": 37,
    "불쌍함/연민": 38,
    "놀람": 39,
    "행복": 40,
    "불안/걱정": 41,
    "기쁨": 42,
    "안심/신뢰": 43
}

In [8]:
import pandas as pd

def emotion_str_to_index_list(emotion_str):
    if pd.isna(emotion_str):
        return []

    emotions = [e.strip() for e in emotion_str.split(",")]
    return [KOTE_EMOTION2IDX[e] for e in emotions if e in KOTE_EMOTION2IDX]

In [10]:
annotator_cols = [
    "annotator_01",
    "annotator_02",
    "annotator_03",
    "annotator_04",
    "annotator_05"
]

for col in annotator_cols:
    df_line[col + "_idx"] = df_line[col].apply(emotion_str_to_index_list)

In [12]:
for col in annotator_cols:
    df_poem[col + "_idx"] = df_poem[col].apply(emotion_str_to_index_list)

In [14]:
POET2IDX = {
    "김소월": 0,
    "윤동주": 1,
    "이상": 2,
    "임화": 3,
    "한용운": 4
}

In [15]:
df_line["poet_idx"] = df_line["poet"].map(POET2IDX)

In [16]:
df_poem["poet_idx"] = df_poem["poet"].map(POET2IDX)

In [30]:
df_line.head()

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔",[11],[11],"[13, 11]","[11, 13, 2]","[11, 36, 5]",1
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함,"[17, 11]","[17, 11, 8, 41, 36, 5]","[29, 11, 13]","[11, 17, 8]",[11],1
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감","[8, 15]","[8, 41, 11]","[5, 36, 41, 33]","[11, 5]","[2, 15, 14, 8]",1
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오","[19, 5, 25]","[19, 5, 25, 30, 27, 11]","[33, 36, 30, 25]","[11, 5, 25, 19, 27]","[5, 36, 19, 27, 25]",1
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복","[42, 15, 28, 32, 13]","[42, 13, 2, 5, 11, 16, 1, 8]","[4, 8, 42, 16, 32]","[2, 8, 42, 16, 40]","[28, 8, 42, 40]",1

In [19]:
df_poem.head()

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움","[41, 11, 36, 5, 10, 17, 30, 25]","[25, 36, 11, 17, 16, 5, 41, 30]","[29, 32, 4, 27, 10]","[11, 13, 5]","[11, 2, 29, 36]",1
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정","[38, 16, 15, 32, 36, 22, 3, 10]","[15, 31, 38, 6, 36, 5, 16, 25]","[10, 36, 5, 29, 32]","[0, 10, 12, 5]","[38, 41]",1
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심","[36, 25, 7, 2, 11, 38, 41, 30]","[2, 39, 38, 11, 5, 40, 16, 41]","[19, 29, 36, 27, 7, 11]","[33, 27, 39, 5, 41]","[29, 11, 7, 15]",1
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침","[5, 36, 20, 25, 30, 17]","[11, 36, 5, 41, 25, 30]","[27, 10, 36, 19, 29]","[27, 33, 41, 0, 5, 17, 25]","[29, 38, 41, 36, 25, 27]",1
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함","[38, 11, 18, 5, 36, 12, 29, 8]","[27, 39, 36, 5, 2, 7, 30, 25, 11, 16]","[19, 29, 36, 27, 10]","[5, 27, 19, 8, 10, 41]","[18, 33, 39, 41, 11]",1

# Mix-Max

In [23]:
from collections import Counter

In [32]:
annotator_cols_idx = [
    "annotator_01_idx",
    "annotator_02_idx",
    "annotator_03_idx",
    "annotator_04_idx",
    "annotator_05_idx"
]

In [35]:
# 함수 정의: 행(row) 단위 감정 주석 Min–Max 스케일링
def minmax_scale_annotations(row, annotator_cols, label_list):
    """
    단일 행(row)에 대해 감정 주석을 Min–Max 스케일링(0.0~1.0)하여 반환합니다.
    각 감정 값은 (해당 감정을 선택한 어노테이터 수 / 전체 어노테이터 수)로 계산됩니다.

    매개변수:
        row (pd.Series): 데이터프레임의 한 행
        annotator_cols (list): 어노테이터 감정 주석이 들어 있는 컬럼 이름 리스트
        label_list (list): 전체 감정 라벨 리스트 (44개 감정)

    반환값:
        dict: {감정라벨: 스케일링된 값} 형태의 딕셔너리
              (어노테이터가 5명인 경우 0, 0.2, 0.4, 0.6, 0.8, 1.0 값만 가능)
    """
    # 각 감정이 몇 번 선택되었는지 카운트하기 위한 Counter 생성
    counts = Counter()
    total = len(annotator_cols)  # 전체 어노테이터 수 (예: 5명)

    # 현재 행의 모든 어노테이터 컬럼을 순회
    for col in annotator_cols:
        ann = row[col]
        if pd.isna(ann):  # NaN이면(주석이 없으면) 건너뛰기
            continue

        # 하나의 셀에 여러 감정이 콤마로 구분되어 있을 경우 분리 후 공백 제거
        labels = [l.strip() for l in str(ann).split(",")]
        counts.update(labels)  # 각 감정의 등장 횟수 누적

    # Min–Max 스케일링 (선택 비율 계산)
    # 예: 슬픔이 3명 → 3 / 5 = 0.6
    scaled = {lab: counts.get(lab, 0) / total for lab in label_list}

    return scaled

In [48]:
# 결과: {감정: 스케일링 값} 형태의 dict가 들어있는 시리즈 생성
scaled_line_outputs = df_line.apply(
    lambda row: minmax_scale_annotations(row, annotator_cols, KOTE_EMOTION2IDX.keys()),
    axis=1
)

# dict 시리즈를 리스트로 변환 후 DataFrame으로 확장
# 최종 결과: 각 감정 라벨이 컬럼으로, 스케일링된 값이 행별로 들어있는 감정 벡터 데이터프레임 생성
scaled_line_df = pd.DataFrame(list(scaled_line_outputs))
scaled_line_df

,불평/불만,환영/호의,감동/감탄,지긋지긋,고마움,슬픔,화남/분노,존경,기대감,우쭐댐/무시함,...,경악,부담/안_내킴,서러움,재미없음,불쌍함/연민,놀람,행복,불안/걱정,기쁨,안심/신뢰
0,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.4,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.2,0.0,0.0
2,0.0,0.0,0.2,0.0,0.0,0.4,0.0,0.0,0.6,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.4,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.8,0.0,0.0,0.0,0.0,...,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.2,0.4,0.0,0.2,0.2,0.0,0.0,0.8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,0.0,0.0,0.2,0.0,0.2,0.4,0.0,0.0,0.0,0.0,...,0.0,0.4,0.0,0.0,0.6,0.2,0.2,0.4,0.2,0.0
7003,0.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.6,0.2,0.0,0.0,0.2,0.0,0.0,0.0,0.0
7004,0.0,0.0,0.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,...,0.4,0.2,0.2,0.0,0.0,0.6,0.0,0.4,0.0,0.2
7005,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.2,0.0,0.2,0.0,0.0
7006,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.4,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0

In [49]:
scaled_line_df = scaled_line_df.rename(
    columns=KOTE_EMOTION2IDX
)

In [50]:
scaled_line_df

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.4,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.2,0.0,0.0
2,0.0,0.0,0.2,0.0,0.0,0.4,0.0,0.0,0.6,0.0,...,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.4,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.8,0.0,0.0,0.0,0.0,...,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.2,0.4,0.0,0.2,0.2,0.0,0.0,0.8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,0.0,0.0,0.2,0.0,0.2,0.4,0.0,0.0,0.0,0.0,...,0.0,0.4,0.0,0.0,0.6,0.2,0.2,0.4,0.2,0.0
7003,0.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.6,0.2,0.0,0.0,0.2,0.0,0.0,0.0,0.0
7004,0.0,0.0,0.0,0.0,0.0,0.4,0.0,0.0,0.0,0.0,...,0.4,0.2,0.2,0.0,0.0,0.6,0.0,0.4,0.0,0.2
7005,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.0,0.2,0.0,0.2,0.0,0.0
7006,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,...,0.0,0.4,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0

In [51]:
# 결과: {감정: 스케일링 값} 형태의 dict가 들어있는 시리즈 생성
scaled_poem_outputs = df_poem.apply(
    lambda row: minmax_scale_annotations(row, annotator_cols, KOTE_EMOTION2IDX.keys()),
    axis=1
)

# dict 시리즈를 리스트로 변환 후 DataFrame으로 확장
# 최종 결과: 각 감정 라벨이 컬럼으로, 스케일링된 값이 행별로 들어있는 감정 벡터 데이터프레임 생성
scaled_poem_df = pd.DataFrame(list(scaled_poem_outputs))

scaled_poem_df = scaled_poem_df.rename(
    columns=KOTE_EMOTION2IDX
)

scaled_poem_df

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,0.0,0.0,0.2,0.0,0.2,0.6,0.0,0.0,0.0,0.0,...,0.0,0.0,0.6,0.0,0.0,0.0,0.0,0.4,0.0,0.0
1,0.2,0.0,0.0,0.2,0.0,0.6,0.2,0.0,0.0,0.0,...,0.0,0.0,0.6,0.0,0.6,0.0,0.0,0.2,0.0,0.0
2,0.0,0.0,0.4,0.0,0.0,0.4,0.0,0.6,0.0,0.0,...,0.0,0.0,0.4,0.0,0.4,0.4,0.2,0.6,0.0,0.0
3,0.2,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,...,0.0,0.0,0.8,0.0,0.2,0.0,0.0,0.6,0.0,0.0
4,0.0,0.0,0.2,0.0,0.0,0.6,0.0,0.2,0.4,0.0,...,0.0,0.0,0.6,0.0,0.2,0.4,0.0,0.4,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,0.4,0.0,0.0,0.2,0.0,0.2,0.0,0.0,0.0,0.0,...,0.4,0.2,0.2,0.0,0.2,0.0,0.0,0.6,0.0,0.0
611,0.0,0.0,0.0,0.4,0.0,0.4,0.0,0.0,0.0,0.0,...,0.2,0.2,0.2,0.2,0.4,0.0,0.0,0.6,0.0,0.0
612,0.0,0.0,0.0,0.4,0.0,0.2,0.2,0.0,0.0,0.0,...,0.6,0.0,0.0,0.0,0.2,0.0,0.0,0.6,0.0,0.0
613,0.2,0.0,0.0,0.0,0.0,0.2,0.2,0.0,0.4,0.2,...,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.8,0.0,0.0
614,0.0,0.2,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,...,0.6,0.0,0.4,0.0,0.0,0.4,0.0,0.6,0.0,0.0

In [52]:
# 각 행에서 0.0보다 큰 값만 딕셔너리로 추출
dict_series = scaled_line_df.apply(lambda row: row[row > 0.0].to_dict(), axis=1)

# Series of dicts → list of dicts
dict_list = dict_series.tolist()

# 각 dict를 value 기준으로 내림차순 정렬
sorted_dict_list = [
    dict(sorted(d.items(), key=lambda x: x[1], reverse=True))
    for d in dict_list
]
sorted_dict_list[:2]

[{11: 1.0, 13: 0.4, 2: 0.2, 5: 0.2, 36: 0.2},
 {11: 1.0, 17: 0.6, 8: 0.4, 5: 0.2, 13: 0.2, 29: 0.2, 36: 0.2, 41: 0.2}]

In [54]:
# dict_list를 'scaled_labels'라는 새 컬럼으로 추가
df_line["scaled_labels"] = sorted_dict_list

In [55]:
df_line

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx,scaled_labels
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔",[11],[11],"[13, 11]","[11, 13, 2]","[11, 36, 5]",1,"{11: 1.0, 13: 0.4, 2: 0.2, 5: 0.2, 36: 0.2}"
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함,"[17, 11]","[17, 11, 8, 41, 36, 5]","[29, 11, 13]","[11, 17, 8]",[11],1,"{11: 1.0, 17: 0.6, 8: 0.4, 5: 0.2, 13: 0.2, 29..."
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감","[8, 15]","[8, 41, 11]","[5, 36, 41, 33]","[11, 5]","[2, 15, 14, 8]",1,"{8: 0.6, 5: 0.4, 11: 0.4, 15: 0.4, 41: 0.4, 2:..."
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오","[19, 5, 25]","[19, 5, 25, 30, 27, 11]","[33, 36, 30, 25]","[11, 5, 25, 19, 27]","[5, 36, 19, 27, 25]",1,"{25: 1.0, 5: 0.8, 19: 0.8, 27: 0.6, 11: 0.4, 3..."
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복","[42, 15, 28, 32, 13]","[42, 13, 2, 5, 11, 16, 1, 8]","[4, 8, 42, 16, 32]","[2, 8, 42, 16, 40]","[28, 8, 42, 40]",1,"{42: 1.0, 8: 0.8, 16: 0.6, 2: 0.4, 13: 0.4, 28..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,7003,483,몸에 반지밖에가지지않은 장난감신부는 어둠을 커―튼열듯하면서 나를찾는다.,2밤,I WED A TOY BRIDE,이상,"불쌍함/연민, 고마움, 슬픔, 패배/자기혐오, 불안/걱정, 의심/불신, 공포/무서움","공포/무서움, 당황/난처, 부담/안_내킴, 불쌍함/연민","놀람, 공포/무서움, 부담/안_내킴","불쌍함/연민, 불안/걱정, 안타까움/실망, 슬픔","감동/감탄, 기쁨, 흐뭇함(귀여움/예쁨), 행복, 즐거움/신남","[38, 4, 5, 25, 41, 12, 18]","[18, 33, 35, 38]","[39, 18, 35]","[38, 41, 10, 5]","[2, 42, 32, 40, 28]",2,"{18: 0.6, 38: 0.6, 5: 0.4, 35: 0.4, 41: 0.4, 2..."
7003,7004,483,얼른 나는 들킨다.,2밤,I WED A TOY BRIDE,이상,"패배/자기혐오, 귀찮음, 지긋지긋, 부담/안_내킴, 죄책감","귀찮음, 패배/자기혐오, 지긋지긋, 절망, 의심/불신, 안타까움/실망, 한심함, 서...","당황/난처, 부끄러움, 부담/안_내킴","놀람, 당황/난처","비장함, 당황/난처, 부담/안_내킴","[25, 26, 3, 35, 30]","[26, 25, 3, 19, 12, 10, 20, 36, 17, 30]","[33, 17, 35]","[39, 33]","[11, 33, 35]",2,"{33: 0.6, 35: 0.6, 3: 0.4, 17: 0.4, 25: 0.4, 2..."
7004,7005,483,반지가살에닿는것을 나는 바늘로잘못알고 아파한다.,2밤,I WED A TOY BRIDE,이상,"의심/불신, 슬픔, 서러움, 패배/자기혐오, 불안/걱정, 죄책감, 한심함, 깨달음,...","공포/무서움, 부담/안_내킴, 불안/걱정, 패배/자기혐오, 한심함, 어이없음, 경악","놀람, 당황/난처","놀람, 당황/난처, 부끄러움, 패배/자기혐오","놀람, 경악, 당황/난처, 부끄러움, 슬픔, 한심함","[12, 5, 36, 25, 41, 30, 20, 29, 33, 43]","[18, 35, 41, 25, 20, 23, 34]","[39, 33]","[39, 33, 17, 25]","[39, 34, 33, 17, 5, 20]",2,"{33: 0.8, 20: 0.6, 25: 0.6, 39: 0.6, 5: 0.4, 1..."
7005,7006,483,촉불을켜고 장난감신부가 밀감을찾는다.,2밤,I WED A TOY BRIDE,이상,"신기함/관심, 없음","신기함/관심, 없음, 놀람","부담/안_내킴, 불안/걱정, 신기함/관심","신기함/관심, 환영/호의, 흐뭇함(귀여움/예쁨)","신기함/관심, 흐뭇함(귀여움/예쁨)","[15, 24]","[15, 24, 39]","[35, 41, 15]","[15, 1, 32]","[15, 32]",2,"{15: 1.0, 24: 0.4, 32: 0.4, 1: 0.2, 35: 0.2, 3..."
7006,7007,483,나는 아파하지않고 모른체한다.,2밤,I WED A TOY BRIDE,이상,"죄책감, 공포/무서움, 의심/불신","의심/불신, 불안/걱정, 당황/난처","부담/안_내킴, 불쌍함/연민, 안타까움/실망","부담/안_내킴, 슬픔, 절망, 힘듦/지침","비장함, 한심함","[30, 18, 12]","[12, 41, 33]","[35, 38, 10]","[35, 5, 19, 27]","[11, 20]",2,"{12: 0.4, 35: 0.4, 5: 0.2, 10: 0.2, 11: 0.2, 1..."

In [53]:
# 각 행에서 0.0보다 큰 값만 딕셔너리로 추출
dict_series1 = scaled_poem_df.apply(lambda row: row[row > 0.0].to_dict(), axis=1)

# Series of dicts → list of dicts
dict_list1 = dict_series1.tolist()

# 각 dict를 value 기준으로 내림차순 정렬
sorted_dict_list1 = [
    dict(sorted(d.items(), key=lambda x: x[1], reverse=True))
    for d in dict_list1
]
sorted_dict_list1[:2]

[{11: 0.8,
  5: 0.6,
  36: 0.6,
  10: 0.4,
  17: 0.4,
  25: 0.4,
  29: 0.4,
  30: 0.4,
  41: 0.4,
  2: 0.2,
  4: 0.2,
  13: 0.2,
  16: 0.2,
  27: 0.2,
  32: 0.2},
 {5: 0.6,
  10: 0.6,
  36: 0.6,
  38: 0.6,
  15: 0.4,
  16: 0.4,
  32: 0.4,
  0: 0.2,
  3: 0.2,
  6: 0.2,
  12: 0.2,
  22: 0.2,
  25: 0.2,
  29: 0.2,
  31: 0.2,
  41: 0.2}]

In [56]:
# dict_list를 'scaled_labels'라는 새 컬럼으로 추가
df_poem["scaled_labels"] = sorted_dict_list1

In [57]:
df_poem

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05,annotator_01_idx,annotator_02_idx,annotator_03_idx,annotator_04_idx,annotator_05_idx,poet_idx,scaled_labels
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움","[41, 11, 36, 5, 10, 17, 30, 25]","[25, 36, 11, 17, 16, 5, 41, 30]","[29, 32, 4, 27, 10]","[11, 13, 5]","[11, 2, 29, 36]",1,"{11: 0.8, 5: 0.6, 36: 0.6, 10: 0.4, 17: 0.4, 2..."
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정","[38, 16, 15, 32, 36, 22, 3, 10]","[15, 31, 38, 6, 36, 5, 16, 25]","[10, 36, 5, 29, 32]","[0, 10, 12, 5]","[38, 41]",1,"{5: 0.6, 10: 0.6, 36: 0.6, 38: 0.6, 15: 0.4, 1..."
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심","[36, 25, 7, 2, 11, 38, 41, 30]","[2, 39, 38, 11, 5, 40, 16, 41]","[19, 29, 36, 27, 7, 11]","[33, 27, 39, 5, 41]","[29, 11, 7, 15]",1,"{11: 0.8, 7: 0.6, 41: 0.6, 2: 0.4, 5: 0.4, 27:..."
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침","[5, 36, 20, 25, 30, 17]","[11, 36, 5, 41, 25, 30]","[27, 10, 36, 19, 29]","[27, 33, 41, 0, 5, 17, 25]","[29, 38, 41, 36, 25, 27]",1,"{25: 0.8, 36: 0.8, 5: 0.6, 27: 0.6, 41: 0.6, 1..."
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함","[38, 11, 18, 5, 36, 12, 29, 8]","[27, 39, 36, 5, 2, 7, 30, 25, 11, 16]","[19, 29, 36, 27, 10]","[5, 27, 19, 8, 10, 41]","[18, 33, 39, 41, 11]",1,"{5: 0.6, 11: 0.6, 27: 0.6, 36: 0.6, 8: 0.4, 10..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,611,482,훤조때문에마멸되는몸이다. 모두가소년이라고들그리는데노야인기색이많다. 혹형에씻기워서산반...,None,가외가전,None,이상,"의심/불신, 불평/불만, 패배/자기혐오, 힘듦/지침, 지긋지긋, 서러움, 공포/무서...","패배/자기혐오, 불쌍함/연민, 공포/무서움, 경악, 불안/걱정, 역겨움/징그러움","깨달음, 불안/걱정, 슬픔, 안타까움/실망, 절망, 패배/자기혐오","경악, 당황/난처, 부담/안_내킴, 힘듦/지침, 절망","힘듦/지침, 불평/불만, 불안/걱정, 깨달음, 절망","[12, 0, 25, 27, 3, 36, 18, 19]","[25, 38, 18, 34, 41, 21]","[29, 41, 5, 10, 19, 25]","[34, 33, 35, 27, 19]","[27, 0, 41, 29, 19]",2,"{19: 0.8, 25: 0.6, 27: 0.6, 41: 0.6, 0: 0.4, 1..."
611,612,482,반추한다. 노파니까. 맞은편평활한유리위에해소된정체를도포한졸음오는혜택이뜬다. 꿈─꿈─...,None,가외가전,None,이상,"깨달음, 서러움, 절망, 의심/불신, 패배/자기혐오, 불안/걱정, 지긋지긋, 힘듦/...","깨달음, 재미없음, 절망, 경악, 역겨움/징그러움, 부담/안_내킴, 불쌍함/연민, ...","불안/걱정, 슬픔, 안타까움/실망, 절망","슬픔, 절망, 힘듦/지침","신기함/관심, 힘듦/지침, 깨달음, 절망, 불안/걱정","[29, 36, 19, 12, 25, 41, 3, 27, 38]","[29, 37, 19, 34, 21, 35, 38, 3, 22]","[41, 5, 10, 19]","[5, 19, 27]","[15, 27, 29, 19, 41]",2,"{19: 1.0, 27: 0.6, 29: 0.6, 41: 0.6, 3: 0.4, 5..."
612,613,482,눈에띄우지않는폭군이잠입하였다는소문이있다. 아기들이번번이애총이되고되고한다. 어디로피해...,None,가외가전,None,이상,"불안/걱정, 지긋지긋, 증오/혐오, 짜증, 화남/분노, 역겨움/징그러움, 절망, 공...","불쌍함/연민, 공포/무서움, 증오/혐오, 역겨움/징그러움, 경악, 당황/난처, 불안...","불안/걱정, 슬픔, 안타까움/실망, 증오/혐오","경악, 공포/무서움, 절망, 패배/자기혐오, 힘듦/지침","역겨움/징그러움, 증오/혐오, 당황/난처, 공포/무서움, 경악, 절망","[41, 3, 31, 22, 6, 21, 19, 18]","[38, 18, 31, 21, 34, 33, 41, 3]","[41, 5, 10, 31]","[34, 18, 19, 25, 27]","[21, 31, 33, 18, 34, 19]",2,"{18: 0.8, 31: 0.8, 19: 0.6, 21: 0.6, 34: 0.6, ..."
613,614,483,장난감신부살결에서 이따금 우유내음새가 나기도한다. 머(ㄹ)지아니하여 아기를낳으려나보...,1밤,I WED A TOY BRIDE,None,이상,"불안/걱정, 힘듦/지침, 아껴주는, 안타까움/실망, 슬픔","기대감, 불안/걱정, 우쭐댐/무시함, 화남/분노, 의심/불신, 힘듦/지침","기대감, 불안/걱정, 아껴주는, 안타까움/실망, 의심/불신","깨달음, 놀람, 불안/걱정, 힘듦/지침","흐뭇함(귀여움/예쁨), 의심/불신, 불평/불만, 짜증","[41, 27, 16, 10, 5]","[8, 41, 9, 6, 12, 27]","[8, 41, 16, 10, 12]","[29, 39, 41, 27]","[32, 12, 0, 22]",2,"{41: 0.8, 12: 0.6, 27: 0.6, 8: 0.4, 10: 0.4, 1..."
614,615,483,장난감신부에게 내가 바늘을주면 장난감신부는 아무것이나 막 찌른다.일력. 시집. 시계...,2밤,I WED A TOY BRIDE,None,이상,"아껴주는, 신기함/관심, 깨달음, 슬픔, 환영/호의, 불안/걱정, 안타까움/실망","불안/걱정, 서러움, 공포/무서움, 아껴주는, 안타까움/실망, 당황/난처, 패배/자...","경악, 놀람, 당황/난처, 불안/걱정, 슬픔, 안타까움/실망, 아껴주는, 패배/자기혐오","당황/난처, 놀람, 경악, 공포/무서움, 절망, 증오/혐오","패배/자기혐오, 당황/난처, 힘듦/지침, 공포/무서움, 경악, 서러움, 슬픔","[16, 15, 29, 5, 1, 41, 10]","[41, 36, 18, 16, 10, 33, 25, 12]","[34, 39, 33, 41, 5, 10, 16, 25]","[33, 39, 34, 18, 19, 31]","[25, 33, 27, 18, 34, 36, 5]",2,"{33: 0.8, 5: 0.6, 10: 0.6, 16: 0.6, 18: 0.6, 2..."

In [58]:
df_line.to_csv(
    "df_line.csv",
    index=False,
    encoding="utf-8-sig"
)

In [59]:
df_poem.to_csv(
    "df_poem.csv",
    index=False,
    encoding="utf-8-sig"
)